name: Backend CIon:
    push:
      branches: [main]
    pull_request:
      branches: [main]jobs:
   deploy-example:
       name: Deploy Blog Example
       if: github.ref == 'refs/heads/main'
       runs-on: ubuntu-latest       steps:
           - uses: actions/checkout@v2
           - name: Configure AWS credentials
             uses: aws-actions/configure-aws-credentials@v1
             with:
                 aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                 aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
                 aws-region: eu-west-2- name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
 
            - name: Build, tag, and push image to Amazon ECR
              id: build-image
              env:
                 ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
                 ECR_REPOSITORY: example
                 IMAGE_TAG: latest
             run: |
                   docker build -t example .
                   docker tag example:latest ${{ secrets.AWS_ACCOUNT_NUM}}.dkr.ecr.eu-west-2.amazonaws.com/example:latest
                   docker push ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.eu-west-2.amazonaws.com/example:latest
                   aws lambda update-function-code --function-name example-lambda --image-uri ${{ secrets.AWS_ACCOUNT_NUM }}.dkr.ecr.eu-west-2.amazonaws.com/example:latest
